# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf9ba18b2cba4594cb18b115a2d6acc66d72cb7d2ec79efa31492bf3ece7cbb95fc4ad5c04d996dec23de60549f300f16e210a9002da4a63f884163872af8db9

test:
  secret_key_base: e61823ad877d3220a12a7a77343d3a21882f2efcf2378b403ef781fbafb7d0521adb546891456323b6ff9a259b26ddfc65f81234107a8fb4952c8681fe867d1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
